---
name: Publish Docker Images
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - run: make build_all
      - run: make publish_all

